# Consumer ProGuard/R8 rules for nitro_camera — automatically applied to any
# app that depends on this plugin.
#
# The block below is regenerated by `nitrogen link` (see
# linkAndroidConsumerRules in nitrogen_cli) — add any of your OWN rules for
# unrelated dependencies outside the BEGIN/END markers; they'll survive.
#
# Why these rules exist: the generated Nitro bridge
# (nitro.nitro_camera_module.NitroCameraJniBridge) and the impl
# (dev.shreeman.nitro_camera.*) are reached from C++ via JNI:
# FindClass("nitro/nitro_camera_module/NitroCameraJniBridge") +
# GetStaticMethodID("create_instance_call", "...") by EXACT name and
# signature. R8 has no way to see those native references, so without these
# rules it may rename, remove, or (in "full mode") mis-optimise them — most
# visibly a VerifyError on a suspend bridge method with several long params
# ("copy-cat2 ... Long (Low Half)") that aborts GeneratedPluginRegistrant
# and leaves the JNI bridge uninitialised → "failed to create native
# instance". includedescriptorclasses is the documented ProGuard fix for
# that: a plain `-keep class X { *; }` protects a member from
# removal/renaming but NOT the parameter/return types referenced in its
# signature — for methods JNI calls by exact signature, an altered
# parameter type produces a VerifyError at the call site even though the
# method itself is "kept".

# --- BEGIN nitrogen-generated JNI keep rules (do not edit by hand — regenerated by `nitrogen link`) ---
# The generated Nitro JNI bridge and its hand-written impl are reached
# from C++ via FindClass + GetStaticMethodID by exact name and signature.
# includedescriptorclasses additionally keeps the parameter/return types
# referenced in those signatures — without it R8 full mode can still
# rename/merge them, producing a VerifyError at the JNI call site even
# though the method itself is "kept". See linkAndroidConsumerRules in
# nitrogen_cli for the full explanation.
-keep,includedescriptorclasses class nitro.nitro_camera_module.** {
    *;
}
-keep,includedescriptorclasses class dev.shreeman.nitro_camera.** {
    *;
}

# JNI resolves native methods (Kotlin `external fun`) by exact name AND
# signature — includedescriptorclasses protects their parameter/return
# types too, not just their names.
-keepclasseswithmembernames,includedescriptorclasses class * {
    native <methods>;
}
# --- END nitrogen-generated JNI keep rules ---

# kotlinx-coroutines-android (>=1.7.0, which this plugin depends on) ships
# its own bundled consumer rules covering Continuation/dispatcher internals
# — do not duplicate those here; doing so would only prevent R8 from
# applying the coroutine-specific optimizations that library's own rules are
# tuned to allow.
