// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.5.5
// Generated from: nitro_camera.native.dart
// ignore_for_file: no_leading_underscores_for_local_identifiers, prefer_typing_uninitialized_variables, non_constant_identifier_names
part of 'nitro_camera.native.dart';

// --- Enum FFI helpers (generated by Nitrogen) ---

extension CameraPositionNativeExt on CameraPosition {
  int get nativeValue => index + 0;
}

extension CameraPositionFromNativeExt on int {
  CameraPosition toCameraPosition() => CameraPosition.values[this - 0];
}

extension CameraLensTypeNativeExt on CameraLensType {
  int get nativeValue => index + 0;
}

extension CameraLensTypeFromNativeExt on int {
  CameraLensType toCameraLensType() => CameraLensType.values[this - 0];
}

extension FlashModeNativeExt on FlashMode {
  int get nativeValue => index + 0;
}

extension FlashModeFromNativeExt on int {
  FlashMode toFlashMode() => FlashMode.values[this - 0];
}

extension AutoFocusModeNativeExt on AutoFocusMode {
  int get nativeValue => index + 0;
}

extension AutoFocusModeFromNativeExt on int {
  AutoFocusMode toAutoFocusMode() => AutoFocusMode.values[this - 0];
}

extension PermissionStatusNativeExt on PermissionStatus {
  int get nativeValue => index + 0;
}

extension PermissionStatusFromNativeExt on int {
  PermissionStatus toPermissionStatus() => PermissionStatus.values[this - 0];
}

extension VideoStabilizationModeNativeExt on VideoStabilizationMode {
  int get nativeValue => index + 0;
}

extension VideoStabilizationModeFromNativeExt on int {
  VideoStabilizationMode toVideoStabilizationMode() =>
      VideoStabilizationMode.values[this - 0];
}

extension QualityPrioritizationNativeExt on QualityPrioritization {
  int get nativeValue => index + 0;
}

extension QualityPrioritizationFromNativeExt on int {
  QualityPrioritization toQualityPrioritization() =>
      QualityPrioritization.values[this - 0];
}

extension VideoCodecNativeExt on VideoCodec {
  int get nativeValue => index + 0;
}

extension VideoCodecFromNativeExt on int {
  VideoCodec toVideoCodec() => VideoCodec.values[this - 0];
}

extension VideoFileTypeNativeExt on VideoFileType {
  int get nativeValue => index + 0;
}

extension VideoFileTypeFromNativeExt on int {
  VideoFileType toVideoFileType() => VideoFileType.values[this - 0];
}

extension CameraEventTypeNativeExt on CameraEventType {
  int get nativeValue => index + 0;
}

extension CameraEventTypeFromNativeExt on int {
  CameraEventType toCameraEventType() => CameraEventType.values[this - 0];
}

extension InterruptionReasonNativeExt on InterruptionReason {
  int get nativeValue => index + 0;
}

extension InterruptionReasonFromNativeExt on int {
  InterruptionReason toInterruptionReason() =>
      InterruptionReason.values[this - 0];
}

// --- Struct FFI representations (generated by Nitrogen) ---

final class CameraFrameFfi extends Struct {
  external Pointer<Uint8> pixels;
  @Int64()
  external int size;
  @Int64()
  external int width;
  @Int64()
  external int height;
  @Int64()
  external int timestamp;
  @Int64()
  external int orientation;
  @Int64()
  external int textureId;
  @Int64()
  external int bytesPerRow;
  @Int64()
  external int pixelFormat;
  @Int64()
  external int isMirrored;
}

extension CameraFrameFfiExt on CameraFrameFfi {
  CameraFrame toDart() {
    return CameraFrame(
      pixels: Uint8List.fromList(pixels.asTypedList(size)),
      size: size,
      width: width,
      height: height,
      timestamp: timestamp,
      orientation: orientation,
      textureId: textureId,
      bytesPerRow: bytesPerRow,
      pixelFormat: pixelFormat,
      isMirrored: isMirrored,
    );
  }

  /// Frees internal fields (like strings) that were allocated on the C heap.
  /// Does NOT free the struct itself.
  void freeFields() {}
}

extension CameraFrameExt on CameraFrame {
  Pointer<CameraFrameFfi> toNative(Arena arena) {
    final ptr = arena<CameraFrameFfi>();
    ptr.ref.pixels = pixels.toPointer(arena);
    ptr.ref.size = size;
    ptr.ref.width = width;
    ptr.ref.height = height;
    ptr.ref.timestamp = timestamp;
    ptr.ref.orientation = orientation;
    ptr.ref.textureId = textureId;
    ptr.ref.bytesPerRow = bytesPerRow;
    ptr.ref.pixelFormat = pixelFormat;
    ptr.ref.isMirrored = isMirrored;
    return ptr;
  }
}

final class CameraConfigFfi extends Struct {
  @Double()
  external double zoom;
  @Double()
  external double exposure;
  @Int64()
  external int flash;
  @Int64()
  external int torch;
  @Double()
  external double torchLevel;
  @Int64()
  external int whiteBalanceKelvin;
  @Int64()
  external int videoHdr;
  @Int64()
  external int lowLightBoost;
  @Int64()
  external int autoFocus;
  @Int64()
  external int videoStabilization;
  @Int64()
  external int active;
  @Int64()
  external int enableFrameProcessing;
  @Int64()
  external int pixelFormat;
  @Int64()
  external int samplingRate;
}

extension CameraConfigFfiExt on CameraConfigFfi {
  CameraConfig toDart() {
    return CameraConfig(
      zoom: zoom,
      exposure: exposure,
      flash: flash,
      torch: torch,
      torchLevel: torchLevel,
      whiteBalanceKelvin: whiteBalanceKelvin,
      videoHdr: videoHdr,
      lowLightBoost: lowLightBoost,
      autoFocus: autoFocus,
      videoStabilization: videoStabilization,
      active: active,
      enableFrameProcessing: enableFrameProcessing,
      pixelFormat: pixelFormat,
      samplingRate: samplingRate,
    );
  }

  /// Frees internal fields (like strings) that were allocated on the C heap.
  /// Does NOT free the struct itself.
  void freeFields() {}
}

extension CameraConfigExt on CameraConfig {
  Pointer<CameraConfigFfi> toNative(Arena arena) {
    final ptr = arena<CameraConfigFfi>();
    ptr.ref.zoom = zoom;
    ptr.ref.exposure = exposure;
    ptr.ref.flash = flash;
    ptr.ref.torch = torch;
    ptr.ref.torchLevel = torchLevel;
    ptr.ref.whiteBalanceKelvin = whiteBalanceKelvin;
    ptr.ref.videoHdr = videoHdr;
    ptr.ref.lowLightBoost = lowLightBoost;
    ptr.ref.autoFocus = autoFocus;
    ptr.ref.videoStabilization = videoStabilization;
    ptr.ref.active = active;
    ptr.ref.enableFrameProcessing = enableFrameProcessing;
    ptr.ref.pixelFormat = pixelFormat;
    ptr.ref.samplingRate = samplingRate;
    return ptr;
  }
}

final class ResolvedConfigFfi extends Struct {
  @Int64()
  external int width;
  @Int64()
  external int height;
  @Int64()
  external int fps;
  @Int64()
  external int pixelFormat;
  @Int64()
  external int videoHdrEnabled;
  @Int64()
  external int autoFocusSystem;
  @Int64()
  external int active;
}

extension ResolvedConfigFfiExt on ResolvedConfigFfi {
  ResolvedConfig toDart() {
    return ResolvedConfig(
      width: width,
      height: height,
      fps: fps,
      pixelFormat: pixelFormat,
      videoHdrEnabled: videoHdrEnabled,
      autoFocusSystem: autoFocusSystem,
      active: active,
    );
  }

  /// Frees internal fields (like strings) that were allocated on the C heap.
  /// Does NOT free the struct itself.
  void freeFields() {}
}

extension ResolvedConfigExt on ResolvedConfig {
  Pointer<ResolvedConfigFfi> toNative(Arena arena) {
    final ptr = arena<ResolvedConfigFfi>();
    ptr.ref.width = width;
    ptr.ref.height = height;
    ptr.ref.fps = fps;
    ptr.ref.pixelFormat = pixelFormat;
    ptr.ref.videoHdrEnabled = videoHdrEnabled;
    ptr.ref.autoFocusSystem = autoFocusSystem;
    ptr.ref.active = active;
    return ptr;
  }
}

final class PhotoOptionsFfi extends Struct {
  @Int64()
  external int flash;
  @Int64()
  external int qualityPrioritization;
  @Int64()
  external int enableShutterSound;
  @Int64()
  external int skipMetadata;
  @Int64()
  external int enableAutoRedEyeReduction;
  @Double()
  external double latitude;
  @Double()
  external double longitude;
  @Double()
  external double altitude;
  @Int64()
  external int hasLocation;
  @Int64()
  external int outputFormat;
}

extension PhotoOptionsFfiExt on PhotoOptionsFfi {
  PhotoOptions toDart() {
    return PhotoOptions(
      flash: flash,
      qualityPrioritization: qualityPrioritization,
      enableShutterSound: enableShutterSound,
      skipMetadata: skipMetadata,
      enableAutoRedEyeReduction: enableAutoRedEyeReduction,
      latitude: latitude,
      longitude: longitude,
      altitude: altitude,
      hasLocation: hasLocation,
      outputFormat: outputFormat,
    );
  }

  /// Frees internal fields (like strings) that were allocated on the C heap.
  /// Does NOT free the struct itself.
  void freeFields() {}
}

extension PhotoOptionsExt on PhotoOptions {
  Pointer<PhotoOptionsFfi> toNative(Arena arena) {
    final ptr = arena<PhotoOptionsFfi>();
    ptr.ref.flash = flash;
    ptr.ref.qualityPrioritization = qualityPrioritization;
    ptr.ref.enableShutterSound = enableShutterSound;
    ptr.ref.skipMetadata = skipMetadata;
    ptr.ref.enableAutoRedEyeReduction = enableAutoRedEyeReduction;
    ptr.ref.latitude = latitude;
    ptr.ref.longitude = longitude;
    ptr.ref.altitude = altitude;
    ptr.ref.hasLocation = hasLocation;
    ptr.ref.outputFormat = outputFormat;
    return ptr;
  }
}

final class RecordingOptionsFfi extends Struct {
  @Int64()
  external int codec;
  @Int64()
  external int fileType;
  @Int64()
  external int bitRate;
  @Int64()
  external int maxDurationMs;
  @Int64()
  external int maxFileSizeBytes;
  @Double()
  external double latitude;
  @Double()
  external double longitude;
  @Double()
  external double altitude;
  @Int64()
  external int hasLocation;
}

extension RecordingOptionsFfiExt on RecordingOptionsFfi {
  RecordingOptions toDart() {
    return RecordingOptions(
      codec: codec,
      fileType: fileType,
      bitRate: bitRate,
      maxDurationMs: maxDurationMs,
      maxFileSizeBytes: maxFileSizeBytes,
      latitude: latitude,
      longitude: longitude,
      altitude: altitude,
      hasLocation: hasLocation,
    );
  }

  /// Frees internal fields (like strings) that were allocated on the C heap.
  /// Does NOT free the struct itself.
  void freeFields() {}
}

extension RecordingOptionsExt on RecordingOptions {
  Pointer<RecordingOptionsFfi> toNative(Arena arena) {
    final ptr = arena<RecordingOptionsFfi>();
    ptr.ref.codec = codec;
    ptr.ref.fileType = fileType;
    ptr.ref.bitRate = bitRate;
    ptr.ref.maxDurationMs = maxDurationMs;
    ptr.ref.maxFileSizeBytes = maxFileSizeBytes;
    ptr.ref.latitude = latitude;
    ptr.ref.longitude = longitude;
    ptr.ref.altitude = altitude;
    ptr.ref.hasLocation = hasLocation;
    return ptr;
  }
}

// --- Struct Native Proxies (zero-copy, lazy field access) ---

/// Zero-copy proxy for [CameraFrame].
/// Extends [CameraFrame] and overrides every getter to read lazily from
/// native memory — no field is copied at construction time.
/// Because `CameraFrameProxy <: CameraFrame`, a `Stream<CameraFrameProxy>`
/// satisfies `Stream<CameraFrame>` via Dart covariant generics.
/// Native memory is freed via a [NativeFinalizer] backed by the
/// generated C symbol 'nitro_camera_release_CameraFrame'.
/// Ownership: this proxy owns the generated struct shell. Zero-copy
/// field buffers remain owned by the native implementation and must
/// stay valid until this proxy is released by the finalizer or
/// [toDartAndRelease].
final class CameraFrameProxy extends CameraFrame implements Finalizable {
  final Pointer<CameraFrameFfi> _native;

  static NativeFinalizer? _finalizer;

  /// Binds the generated release symbol from [dylib].
  /// Must be called once — typically in the impl class constructor.
  /// Idempotent: subsequent calls are a no-op.
  static void _init(DynamicLibrary dylib) {
    _finalizer ??= NativeFinalizer(
      dylib.lookup<NativeFunction<Void Function(Pointer<Void>)>>(
        'nitro_camera_release_CameraFrame',
      ),
    );
  }

  /// Takes ownership of [native]. Super fields are zeroed and never read;
  /// all getters below are overridden to read from native memory instead.
  /// Do NOT call [malloc.free] on the struct shell after passing it here,
  /// and do not free zero-copy field buffers while the proxy may be read.
  CameraFrameProxy(this._native)
    : super(
        pixels: Uint8List(0),
        size: 0,
        width: 0,
        height: 0,
        timestamp: 0,
        orientation: 0,
        textureId: 0,
        bytesPerRow: 0,
        pixelFormat: 0,
        isMirrored: 0,
      ) {
    assert(
      _finalizer != null,
      'CameraFrameProxy._init() was not called. Ensure the Nitro impl class constructor ran before creating proxies.',
    );
    _finalizer!.attach(this, _native.cast(), detach: this, externalSize: 512);
  }

  // @override lazy getters — read native memory on demand, zero allocation.
  @override
  Uint8List get pixels => _native.ref.pixels.asTypedList(_native.ref.size);
  @override
  int get size => _native.ref.size;
  @override
  int get width => _native.ref.width;
  @override
  int get height => _native.ref.height;
  @override
  int get timestamp => _native.ref.timestamp;
  @override
  int get orientation => _native.ref.orientation;
  @override
  int get textureId => _native.ref.textureId;
  @override
  int get bytesPerRow => _native.ref.bytesPerRow;
  @override
  int get pixelFormat => _native.ref.pixelFormat;
  @override
  int get isMirrored => _native.ref.isMirrored;

  /// Eagerly copies all fields to a plain [CameraFrame] value, detaches
  /// the finalizer, and frees native memory immediately.
  /// Use this only when you need an immutable snapshot; for streams
  /// prefer consuming the proxy fields lazily then letting it GC.
  /// Must not be called more than once.
  CameraFrame toDartAndRelease() {
    final v = _native.ref.toDart();
    _finalizer?.detach(this);
    malloc.free(_native);
    return v;
  }
}

/// Zero-copy proxy for [CameraConfig].
/// Extends [CameraConfig] and overrides every getter to read lazily from
/// native memory — no field is copied at construction time.
/// Because `CameraConfigProxy <: CameraConfig`, a `Stream<CameraConfigProxy>`
/// satisfies `Stream<CameraConfig>` via Dart covariant generics.
/// Native memory is freed via a [NativeFinalizer] backed by the
/// generated C symbol 'nitro_camera_release_CameraConfig'.
/// Ownership: this proxy owns the generated struct shell. Zero-copy
/// field buffers remain owned by the native implementation and must
/// stay valid until this proxy is released by the finalizer or
/// [toDartAndRelease].
final class CameraConfigProxy extends CameraConfig implements Finalizable {
  final Pointer<CameraConfigFfi> _native;

  static NativeFinalizer? _finalizer;

  /// Binds the generated release symbol from [dylib].
  /// Must be called once — typically in the impl class constructor.
  /// Idempotent: subsequent calls are a no-op.
  static void _init(DynamicLibrary dylib) {
    _finalizer ??= NativeFinalizer(
      dylib.lookup<NativeFunction<Void Function(Pointer<Void>)>>(
        'nitro_camera_release_CameraConfig',
      ),
    );
  }

  /// Takes ownership of [native]. Super fields are zeroed and never read;
  /// all getters below are overridden to read from native memory instead.
  /// Do NOT call [malloc.free] on the struct shell after passing it here,
  /// and do not free zero-copy field buffers while the proxy may be read.
  CameraConfigProxy(this._native)
    : super(
        zoom: 0.0,
        exposure: 0.0,
        flash: 0,
        torch: 0,
        torchLevel: 0.0,
        whiteBalanceKelvin: 0,
        videoHdr: 0,
        lowLightBoost: 0,
        autoFocus: 0,
        videoStabilization: 0,
        active: 0,
        enableFrameProcessing: 0,
        pixelFormat: 0,
        samplingRate: 0,
      ) {
    assert(
      _finalizer != null,
      'CameraConfigProxy._init() was not called. Ensure the Nitro impl class constructor ran before creating proxies.',
    );
    _finalizer!.attach(this, _native.cast(), detach: this, externalSize: 512);
  }

  // @override lazy getters — read native memory on demand, zero allocation.
  @override
  double get zoom => _native.ref.zoom;
  @override
  double get exposure => _native.ref.exposure;
  @override
  int get flash => _native.ref.flash;
  @override
  int get torch => _native.ref.torch;
  @override
  double get torchLevel => _native.ref.torchLevel;
  @override
  int get whiteBalanceKelvin => _native.ref.whiteBalanceKelvin;
  @override
  int get videoHdr => _native.ref.videoHdr;
  @override
  int get lowLightBoost => _native.ref.lowLightBoost;
  @override
  int get autoFocus => _native.ref.autoFocus;
  @override
  int get videoStabilization => _native.ref.videoStabilization;
  @override
  int get active => _native.ref.active;
  @override
  int get enableFrameProcessing => _native.ref.enableFrameProcessing;
  @override
  int get pixelFormat => _native.ref.pixelFormat;
  @override
  int get samplingRate => _native.ref.samplingRate;

  /// Eagerly copies all fields to a plain [CameraConfig] value, detaches
  /// the finalizer, and frees native memory immediately.
  /// Use this only when you need an immutable snapshot; for streams
  /// prefer consuming the proxy fields lazily then letting it GC.
  /// Must not be called more than once.
  CameraConfig toDartAndRelease() {
    final v = _native.ref.toDart();
    _finalizer?.detach(this);
    malloc.free(_native);
    return v;
  }
}

/// Zero-copy proxy for [ResolvedConfig].
/// Extends [ResolvedConfig] and overrides every getter to read lazily from
/// native memory — no field is copied at construction time.
/// Because `ResolvedConfigProxy <: ResolvedConfig`, a `Stream<ResolvedConfigProxy>`
/// satisfies `Stream<ResolvedConfig>` via Dart covariant generics.
/// Native memory is freed via a [NativeFinalizer] backed by the
/// generated C symbol 'nitro_camera_release_ResolvedConfig'.
/// Ownership: this proxy owns the generated struct shell. Zero-copy
/// field buffers remain owned by the native implementation and must
/// stay valid until this proxy is released by the finalizer or
/// [toDartAndRelease].
final class ResolvedConfigProxy extends ResolvedConfig implements Finalizable {
  final Pointer<ResolvedConfigFfi> _native;

  static NativeFinalizer? _finalizer;

  /// Binds the generated release symbol from [dylib].
  /// Must be called once — typically in the impl class constructor.
  /// Idempotent: subsequent calls are a no-op.
  static void _init(DynamicLibrary dylib) {
    _finalizer ??= NativeFinalizer(
      dylib.lookup<NativeFunction<Void Function(Pointer<Void>)>>(
        'nitro_camera_release_ResolvedConfig',
      ),
    );
  }

  /// Takes ownership of [native]. Super fields are zeroed and never read;
  /// all getters below are overridden to read from native memory instead.
  /// Do NOT call [malloc.free] on the struct shell after passing it here,
  /// and do not free zero-copy field buffers while the proxy may be read.
  ResolvedConfigProxy(this._native)
    : super(
        width: 0,
        height: 0,
        fps: 0,
        pixelFormat: 0,
        videoHdrEnabled: 0,
        autoFocusSystem: 0,
        active: 0,
      ) {
    assert(
      _finalizer != null,
      'ResolvedConfigProxy._init() was not called. Ensure the Nitro impl class constructor ran before creating proxies.',
    );
    _finalizer!.attach(this, _native.cast(), detach: this, externalSize: 512);
  }

  // @override lazy getters — read native memory on demand, zero allocation.
  @override
  int get width => _native.ref.width;
  @override
  int get height => _native.ref.height;
  @override
  int get fps => _native.ref.fps;
  @override
  int get pixelFormat => _native.ref.pixelFormat;
  @override
  int get videoHdrEnabled => _native.ref.videoHdrEnabled;
  @override
  int get autoFocusSystem => _native.ref.autoFocusSystem;
  @override
  int get active => _native.ref.active;

  /// Eagerly copies all fields to a plain [ResolvedConfig] value, detaches
  /// the finalizer, and frees native memory immediately.
  /// Use this only when you need an immutable snapshot; for streams
  /// prefer consuming the proxy fields lazily then letting it GC.
  /// Must not be called more than once.
  ResolvedConfig toDartAndRelease() {
    final v = _native.ref.toDart();
    _finalizer?.detach(this);
    malloc.free(_native);
    return v;
  }
}

/// Zero-copy proxy for [PhotoOptions].
/// Extends [PhotoOptions] and overrides every getter to read lazily from
/// native memory — no field is copied at construction time.
/// Because `PhotoOptionsProxy <: PhotoOptions`, a `Stream<PhotoOptionsProxy>`
/// satisfies `Stream<PhotoOptions>` via Dart covariant generics.
/// Native memory is freed via a [NativeFinalizer] backed by the
/// generated C symbol 'nitro_camera_release_PhotoOptions'.
/// Ownership: this proxy owns the generated struct shell. Zero-copy
/// field buffers remain owned by the native implementation and must
/// stay valid until this proxy is released by the finalizer or
/// [toDartAndRelease].
final class PhotoOptionsProxy extends PhotoOptions implements Finalizable {
  final Pointer<PhotoOptionsFfi> _native;

  static NativeFinalizer? _finalizer;

  /// Binds the generated release symbol from [dylib].
  /// Must be called once — typically in the impl class constructor.
  /// Idempotent: subsequent calls are a no-op.
  static void _init(DynamicLibrary dylib) {
    _finalizer ??= NativeFinalizer(
      dylib.lookup<NativeFunction<Void Function(Pointer<Void>)>>(
        'nitro_camera_release_PhotoOptions',
      ),
    );
  }

  /// Takes ownership of [native]. Super fields are zeroed and never read;
  /// all getters below are overridden to read from native memory instead.
  /// Do NOT call [malloc.free] on the struct shell after passing it here,
  /// and do not free zero-copy field buffers while the proxy may be read.
  PhotoOptionsProxy(this._native)
    : super(
        flash: 0,
        qualityPrioritization: 0,
        enableShutterSound: 0,
        skipMetadata: 0,
        enableAutoRedEyeReduction: 0,
        latitude: 0.0,
        longitude: 0.0,
        altitude: 0.0,
        hasLocation: 0,
        outputFormat: 0,
      ) {
    assert(
      _finalizer != null,
      'PhotoOptionsProxy._init() was not called. Ensure the Nitro impl class constructor ran before creating proxies.',
    );
    _finalizer!.attach(this, _native.cast(), detach: this, externalSize: 512);
  }

  // @override lazy getters — read native memory on demand, zero allocation.
  @override
  int get flash => _native.ref.flash;
  @override
  int get qualityPrioritization => _native.ref.qualityPrioritization;
  @override
  int get enableShutterSound => _native.ref.enableShutterSound;
  @override
  int get skipMetadata => _native.ref.skipMetadata;
  @override
  int get enableAutoRedEyeReduction => _native.ref.enableAutoRedEyeReduction;
  @override
  double get latitude => _native.ref.latitude;
  @override
  double get longitude => _native.ref.longitude;
  @override
  double get altitude => _native.ref.altitude;
  @override
  int get hasLocation => _native.ref.hasLocation;
  @override
  int get outputFormat => _native.ref.outputFormat;

  /// Eagerly copies all fields to a plain [PhotoOptions] value, detaches
  /// the finalizer, and frees native memory immediately.
  /// Use this only when you need an immutable snapshot; for streams
  /// prefer consuming the proxy fields lazily then letting it GC.
  /// Must not be called more than once.
  PhotoOptions toDartAndRelease() {
    final v = _native.ref.toDart();
    _finalizer?.detach(this);
    malloc.free(_native);
    return v;
  }
}

/// Zero-copy proxy for [RecordingOptions].
/// Extends [RecordingOptions] and overrides every getter to read lazily from
/// native memory — no field is copied at construction time.
/// Because `RecordingOptionsProxy <: RecordingOptions`, a `Stream<RecordingOptionsProxy>`
/// satisfies `Stream<RecordingOptions>` via Dart covariant generics.
/// Native memory is freed via a [NativeFinalizer] backed by the
/// generated C symbol 'nitro_camera_release_RecordingOptions'.
/// Ownership: this proxy owns the generated struct shell. Zero-copy
/// field buffers remain owned by the native implementation and must
/// stay valid until this proxy is released by the finalizer or
/// [toDartAndRelease].
final class RecordingOptionsProxy extends RecordingOptions
    implements Finalizable {
  final Pointer<RecordingOptionsFfi> _native;

  static NativeFinalizer? _finalizer;

  /// Binds the generated release symbol from [dylib].
  /// Must be called once — typically in the impl class constructor.
  /// Idempotent: subsequent calls are a no-op.
  static void _init(DynamicLibrary dylib) {
    _finalizer ??= NativeFinalizer(
      dylib.lookup<NativeFunction<Void Function(Pointer<Void>)>>(
        'nitro_camera_release_RecordingOptions',
      ),
    );
  }

  /// Takes ownership of [native]. Super fields are zeroed and never read;
  /// all getters below are overridden to read from native memory instead.
  /// Do NOT call [malloc.free] on the struct shell after passing it here,
  /// and do not free zero-copy field buffers while the proxy may be read.
  RecordingOptionsProxy(this._native)
    : super(
        codec: 0,
        fileType: 0,
        bitRate: 0,
        maxDurationMs: 0,
        maxFileSizeBytes: 0,
        latitude: 0.0,
        longitude: 0.0,
        altitude: 0.0,
        hasLocation: 0,
      ) {
    assert(
      _finalizer != null,
      'RecordingOptionsProxy._init() was not called. Ensure the Nitro impl class constructor ran before creating proxies.',
    );
    _finalizer!.attach(this, _native.cast(), detach: this, externalSize: 512);
  }

  // @override lazy getters — read native memory on demand, zero allocation.
  @override
  int get codec => _native.ref.codec;
  @override
  int get fileType => _native.ref.fileType;
  @override
  int get bitRate => _native.ref.bitRate;
  @override
  int get maxDurationMs => _native.ref.maxDurationMs;
  @override
  int get maxFileSizeBytes => _native.ref.maxFileSizeBytes;
  @override
  double get latitude => _native.ref.latitude;
  @override
  double get longitude => _native.ref.longitude;
  @override
  double get altitude => _native.ref.altitude;
  @override
  int get hasLocation => _native.ref.hasLocation;

  /// Eagerly copies all fields to a plain [RecordingOptions] value, detaches
  /// the finalizer, and frees native memory immediately.
  /// Use this only when you need an immutable snapshot; for streams
  /// prefer consuming the proxy fields lazily then letting it GC.
  /// Must not be called more than once.
  RecordingOptions toDartAndRelease() {
    final v = _native.ref.toDart();
    _finalizer?.detach(this);
    malloc.free(_native);
    return v;
  }
}

// --- @HybridRecord binary extensions (generated by Nitrogen) ---

extension CameraDeviceRecordExt on CameraDevice {
  static CameraDevice fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static CameraDevice fromReader(RecordReader r) => CameraDevice(
    id: r.readString(),
    name: r.readString(),
    position: r.readInt(),
    lensType: r.readInt(),
    sensorOrientation: r.readInt(),
    minZoom: r.readDouble(),
    maxZoom: r.readDouble(),
    neutralZoom: r.readDouble(),
    hasFlash: r.readInt(),
    hasTorch: r.readInt(),
    maxPhotoWidth: r.readInt(),
    maxPhotoHeight: r.readInt(),
    focalLength: r.readDouble(),
    aperture: r.readDouble(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeString(id);
    writer.writeString(name);
    writer.writeInt(position);
    writer.writeInt(lensType);
    writer.writeInt(sensorOrientation);
    writer.writeDouble(minZoom);
    writer.writeDouble(maxZoom);
    writer.writeDouble(neutralZoom);
    writer.writeInt(hasFlash);
    writer.writeInt(hasTorch);
    writer.writeInt(maxPhotoWidth);
    writer.writeInt(maxPhotoHeight);
    writer.writeDouble(focalLength);
    writer.writeDouble(aperture);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension PhotoResultRecordExt on PhotoResult {
  static PhotoResult fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static PhotoResult fromReader(RecordReader r) => PhotoResult(
    path: r.readString(),
    width: r.readInt(),
    height: r.readInt(),
    fileSize: r.readInt(),
    orientation: r.readInt(),
    isMirrored: r.readInt(),
    timestamp: r.readInt(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeString(path);
    writer.writeInt(width);
    writer.writeInt(height);
    writer.writeInt(fileSize);
    writer.writeInt(orientation);
    writer.writeInt(isMirrored);
    writer.writeInt(timestamp);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension RecordingResultRecordExt on RecordingResult {
  static RecordingResult fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static RecordingResult fromReader(RecordReader r) => RecordingResult(
    path: r.readString(),
    durationMs: r.readInt(),
    fileSize: r.readInt(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeString(path);
    writer.writeInt(durationMs);
    writer.writeInt(fileSize);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension CameraEventRecordExt on CameraEvent {
  static CameraEvent fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static CameraEvent fromReader(RecordReader r) => CameraEvent(
    type: r.readInt(),
    textureId: r.readInt(),
    reason: r.readInt(),
    message: r.readString(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeInt(type);
    writer.writeInt(textureId);
    writer.writeInt(reason);
    writer.writeString(message);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

class _NitroCameraImpl extends NitroCamera {
  final DynamicLibrary _dylib;
  static final _instances = <String, _NitroCameraImpl>{};
  final String _instanceKey;
  late final int _instanceId;
  final Pointer<NitroErrorFfi> _nitroErr = calloc<NitroErrorFfi>();

  static DynamicLibrary _loadSupportedLibrary() {
    return NitroRuntime.loadLibForTargets(
      'nitro_camera',
      ios: true,
      android: true,
      macos: false,
      windows: false,
      linux: false,
      web: false,
    );
  }

  factory _NitroCameraImpl([String key = 'default']) {
    return _instances.putIfAbsent(key, () => _NitroCameraImpl._init(key));
  }

  _NitroCameraImpl._init(this._instanceKey) : _dylib = _loadSupportedLibrary() {
    final initSw = Stopwatch()..start();
    assert(
      sizeOf<IntPtr>() >= 4,
      'nitro_camera: unsupported pointer width ${sizeOf<IntPtr>()}B',
    );
    final initFunc = _dylib
        .lookupFunction<
          IntPtr Function(Pointer<Void>),
          int Function(Pointer<Void>)
        >('nitro_camera_init_dart_api_dl');
    final initCode = initFunc(NativeApi.initializeApiDLData);
    if (initCode != 0) {
      throw StateError(
        'nitro_camera: Dart API DL initialization failed with code $initCode.',
      );
    }
    if (!_dylib.providesSymbol('nitro_camera_nitro_abi_version')) {
      throw StateError(
        'nitro_camera: missing nitro_camera_nitro_abi_version — plugin must be rebuilt against the current Nitro version.',
      );
    }
    NitroRuntime.checkAbiVersion(
      'nitro_camera',
      () => _dylib.lookupFunction<Uint32 Function(), int Function()>(
        'nitro_camera_nitro_abi_version',
      )(),
    );
    if (!_dylib.providesSymbol('nitro_camera_nitro_bridge_checksum')) {
      throw StateError(
        'nitro_camera: missing nitro_camera_nitro_bridge_checksum — plugin must be rebuilt against the current Nitro version.',
      );
    }
    NitroRuntime.checkLinkChecksum(
      'nitro_camera',
      '1fa675a20dfada8b',
      () => _dylib
          .lookupFunction<Pointer<Utf8> Function(), Pointer<Utf8> Function()>(
            'nitro_camera_nitro_bridge_checksum',
          )()
          .toDartString(),
    );
    CameraFrameProxy._init(_dylib);
    CameraConfigProxy._init(_dylib);
    ResolvedConfigProxy._init(_dylib);
    PhotoOptionsProxy._init(_dylib);
    RecordingOptionsProxy._init(_dylib);
    final _keyPtr = _instanceKey.toNativeUtf8(allocator: calloc);
    try {
      _instanceId = _createInstancePtr(_keyPtr);
      if (_instanceId < 0) {
        throw StateError(
          'nitro_camera: failed to create native instance for key "$_instanceKey".',
        );
      }
    } finally {
      calloc.free(_keyPtr);
    }
    NitroInstanceRegistry.register(_instanceId, this);
    initSw.stop();
    NitroRuntime.logLifecycle(
      'init(nitro_camera)',
      'initialized in ${initSw.elapsedMicroseconds} µs (instanceId=$_instanceId)',
    );
  }

  late final int Function(Pointer<Utf8>) _createInstancePtr = _dylib
      .lookupFunction<
        Int64 Function(Pointer<Utf8>),
        int Function(Pointer<Utf8>)
      >('nitro_camera_create_instance');
  late final void Function(int) _destroyInstancePtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_camera_destroy_instance',
      );
  late final int Function(int) _requestCameraPermissionPtr = _dylib
      .lookupFunction<Int64 Function(Int64), int Function(int)>(
        'nitro_camera_request_camera_permission',
      );
  late final int Function(int, Pointer<NitroErrorFfi>)
  _getCameraPermissionStatusPtr = _dylib
      .lookup<NativeFunction<Int64 Function(Int64, Pointer<NitroErrorFfi>)>>(
        'nitro_camera_get_camera_permission_status',
      )
      .asFunction<int Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final int Function(int) _requestMicrophonePermissionPtr = _dylib
      .lookupFunction<Int64 Function(Int64), int Function(int)>(
        'nitro_camera_request_microphone_permission',
      );
  late final int Function(int, Pointer<NitroErrorFfi>)
  _getMicrophonePermissionStatusPtr = _dylib
      .lookup<NativeFunction<Int64 Function(Int64, Pointer<NitroErrorFfi>)>>(
        'nitro_camera_get_microphone_permission_status',
      )
      .asFunction<int Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final Pointer<Utf8> Function(int) _getAvailableCameraDevicesJsonPtr =
      _dylib.lookupFunction<
        Pointer<Utf8> Function(Int64),
        Pointer<Utf8> Function(int)
      >('nitro_camera_get_available_camera_devices_json');
  late final Pointer<Uint8> Function(int, Pointer<NitroErrorFfi>)
  _getAvailableCameraDevicesPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Int64, Pointer<NitroErrorFfi>),
        Pointer<Uint8> Function(int, Pointer<NitroErrorFfi>)
      >('nitro_camera_get_available_camera_devices');
  late final int Function(int, Pointer<NitroErrorFfi>)
  _getDeviceCountPtr = _dylib
      .lookup<NativeFunction<Int64 Function(Int64, Pointer<NitroErrorFfi>)>>(
        'nitro_camera_get_device_count',
      )
      .asFunction<int Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final Pointer<Uint8> Function(int, int, Pointer<NitroErrorFfi>)
  _getDevicePtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Int64, Int64, Pointer<NitroErrorFfi>),
        Pointer<Uint8> Function(int, int, Pointer<NitroErrorFfi>)
      >('nitro_camera_get_device');
  late final int Function(int, Pointer<Utf8>, int, int, int, int)
  _openCameraPtr = _dylib
      .lookupFunction<
        Int64 Function(Int64, Pointer<Utf8>, Int64, Int64, Int64, Int64),
        int Function(int, Pointer<Utf8>, int, int, int, int)
      >('nitro_camera_open_camera');
  late final void Function(int, int) _closeCameraPtr = _dylib
      .lookupFunction<Void Function(Int64, Int64), void Function(int, int)>(
        'nitro_camera_close_camera',
      );
  late final void Function(int, int, Pointer<NitroErrorFfi>) _startPreviewPtr =
      _dylib
          .lookup<
            NativeFunction<Void Function(Int64, Int64, Pointer<NitroErrorFfi>)>
          >('nitro_camera_start_preview')
          .asFunction<void Function(int, int, Pointer<NitroErrorFfi>)>(
            isLeaf: true,
          );
  late final void Function(int, int, Pointer<NitroErrorFfi>) _stopPreviewPtr =
      _dylib
          .lookup<
            NativeFunction<Void Function(Int64, Int64, Pointer<NitroErrorFfi>)>
          >('nitro_camera_stop_preview')
          .asFunction<void Function(int, int, Pointer<NitroErrorFfi>)>(
            isLeaf: true,
          );
  late final void Function(int, int, double, Pointer<NitroErrorFfi>)
  _setZoomPtr = _dylib
      .lookup<
        NativeFunction<
          Void Function(Int64, Int64, Double, Pointer<NitroErrorFfi>)
        >
      >('nitro_camera_set_zoom')
      .asFunction<void Function(int, int, double, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final void Function(int, int, double, double, Pointer<NitroErrorFfi>)
  _setFocusPointPtr = _dylib
      .lookup<
        NativeFunction<
          Void Function(Int64, Int64, Double, Double, Pointer<NitroErrorFfi>)
        >
      >('nitro_camera_set_focus_point')
      .asFunction<
        void Function(int, int, double, double, Pointer<NitroErrorFfi>)
      >(isLeaf: true);
  late final void Function(int, int, int, Pointer<NitroErrorFfi>)
  _setAutoFocusPtr = _dylib
      .lookup<
        NativeFunction<
          Void Function(Int64, Int64, Int64, Pointer<NitroErrorFfi>)
        >
      >('nitro_camera_set_auto_focus')
      .asFunction<void Function(int, int, int, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final void Function(int, int, double, Pointer<NitroErrorFfi>)
  _setExposurePtr = _dylib
      .lookup<
        NativeFunction<
          Void Function(Int64, Int64, Double, Pointer<NitroErrorFfi>)
        >
      >('nitro_camera_set_exposure')
      .asFunction<void Function(int, int, double, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final void Function(int, int, int, Pointer<NitroErrorFfi>) _setFlashPtr =
      _dylib
          .lookup<
            NativeFunction<
              Void Function(Int64, Int64, Int64, Pointer<NitroErrorFfi>)
            >
          >('nitro_camera_set_flash')
          .asFunction<void Function(int, int, int, Pointer<NitroErrorFfi>)>(
            isLeaf: true,
          );
  late final void Function(int, int, int, Pointer<NitroErrorFfi>) _setTorchPtr =
      _dylib
          .lookup<
            NativeFunction<
              Void Function(Int64, Int64, Int64, Pointer<NitroErrorFfi>)
            >
          >('nitro_camera_set_torch')
          .asFunction<void Function(int, int, int, Pointer<NitroErrorFfi>)>(
            isLeaf: true,
          );
  late final void Function(int, int, int, Pointer<NitroErrorFfi>)
  _setWhiteBalancePtr = _dylib
      .lookup<
        NativeFunction<
          Void Function(Int64, Int64, Int64, Pointer<NitroErrorFfi>)
        >
      >('nitro_camera_set_white_balance')
      .asFunction<void Function(int, int, int, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final void Function(int, int, int, Pointer<NitroErrorFfi>) _setHdrPtr =
      _dylib
          .lookup<
            NativeFunction<
              Void Function(Int64, Int64, Int64, Pointer<NitroErrorFfi>)
            >
          >('nitro_camera_set_hdr')
          .asFunction<void Function(int, int, int, Pointer<NitroErrorFfi>)>(
            isLeaf: true,
          );
  late final Pointer<Uint8> Function(int, int) _takePhotoPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Int64, Int64),
        Pointer<Uint8> Function(int, int)
      >('nitro_camera_take_photo');
  late final void Function(int, int, Pointer<Utf8>, Pointer<Void>)
  _startVideoRecordingPtr = _dylib
      .lookupFunction<
        Void Function(Int64, Int64, Pointer<Utf8>, Pointer<Void>),
        void Function(int, int, Pointer<Utf8>, Pointer<Void>)
      >('nitro_camera_start_video_recording');
  late final Pointer<Uint8> Function(int, int) _stopVideoRecordingPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Int64, Int64),
        Pointer<Uint8> Function(int, int)
      >('nitro_camera_stop_video_recording');
  late final void Function(int, int, Pointer<NitroErrorFfi>)
  _pauseRecordingPtr = _dylib
      .lookup<
        NativeFunction<Void Function(Int64, Int64, Pointer<NitroErrorFfi>)>
      >('nitro_camera_pause_recording')
      .asFunction<void Function(int, int, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final void Function(int, int, Pointer<NitroErrorFfi>)
  _resumeRecordingPtr = _dylib
      .lookup<
        NativeFunction<Void Function(Int64, Int64, Pointer<NitroErrorFfi>)>
      >('nitro_camera_resume_recording')
      .asFunction<void Function(int, int, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final void Function(int, int, Pointer<NitroErrorFfi>)
  _cancelRecordingPtr = _dylib
      .lookup<
        NativeFunction<Void Function(Int64, Int64, Pointer<NitroErrorFfi>)>
      >('nitro_camera_cancel_recording')
      .asFunction<void Function(int, int, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final void Function(int, int, int, Pointer<NitroErrorFfi>)
  _enableFrameProcessingPtr = _dylib
      .lookup<
        NativeFunction<
          Void Function(Int64, Int64, Int64, Pointer<NitroErrorFfi>)
        >
      >('nitro_camera_enable_frame_processing')
      .asFunction<void Function(int, int, int, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final void Function(int, int, int, Pointer<NitroErrorFfi>)
  _setFrameFormatPtr = _dylib
      .lookup<
        NativeFunction<
          Void Function(Int64, Int64, Int64, Pointer<NitroErrorFfi>)
        >
      >('nitro_camera_set_frame_format')
      .asFunction<void Function(int, int, int, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final void Function(int, int, int, Pointer<NitroErrorFfi>)
  _setSamplingRatePtr = _dylib
      .lookup<
        NativeFunction<
          Void Function(Int64, Int64, Int64, Pointer<NitroErrorFfi>)
        >
      >('nitro_camera_set_sampling_rate')
      .asFunction<void Function(int, int, int, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final void Function(int, int, Pointer<Utf8>, Pointer<NitroErrorFfi>)
  _setFilterShaderPtr = _dylib
      .lookupFunction<
        Void Function(Int64, Int64, Pointer<Utf8>, Pointer<NitroErrorFfi>),
        void Function(int, int, Pointer<Utf8>, Pointer<NitroErrorFfi>)
      >('nitro_camera_set_filter_shader');
  late final void Function(
    int,
    int,
    Pointer<Uint8>,
    int,
    Pointer<NitroErrorFfi>,
  )
  _updateOverlayPtr = _dylib
      .lookupFunction<
        Void Function(
          Int64,
          Int64,
          Pointer<Uint8>,
          Size,
          Pointer<NitroErrorFfi>,
        ),
        void Function(int, int, Pointer<Uint8>, int, Pointer<NitroErrorFfi>)
      >('nitro_camera_update_overlay');
  late final Pointer<Void> Function(int, int, Pointer<Void>) _configurePtr =
      _dylib.lookupFunction<
        Pointer<Void> Function(Int64, Int64, Pointer<Void>),
        Pointer<Void> Function(int, int, Pointer<Void>)
      >('nitro_camera_configure');
  late final Pointer<Utf8> Function(int, int, Pointer<NitroErrorFfi>)
  _getSessionStateJsonPtr = _dylib
      .lookupFunction<
        Pointer<Utf8> Function(Int64, Int64, Pointer<NitroErrorFfi>),
        Pointer<Utf8> Function(int, int, Pointer<NitroErrorFfi>)
      >('nitro_camera_get_session_state_json');
  late final void Function(int, int, int, Pointer<NitroErrorFfi>)
  _setVideoStabilizationPtr = _dylib
      .lookup<
        NativeFunction<
          Void Function(Int64, Int64, Int64, Pointer<NitroErrorFfi>)
        >
      >('nitro_camera_set_video_stabilization')
      .asFunction<void Function(int, int, int, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final void Function(int, int, int, Pointer<NitroErrorFfi>)
  _setLowLightBoostPtr = _dylib
      .lookup<
        NativeFunction<
          Void Function(Int64, Int64, Int64, Pointer<NitroErrorFfi>)
        >
      >('nitro_camera_set_low_light_boost')
      .asFunction<void Function(int, int, int, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final void Function(int, int, double, Pointer<NitroErrorFfi>)
  _setTorchLevelPtr = _dylib
      .lookup<
        NativeFunction<
          Void Function(Int64, Int64, Double, Pointer<NitroErrorFfi>)
        >
      >('nitro_camera_set_torch_level')
      .asFunction<void Function(int, int, double, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final void Function(int, int, int, Pointer<NitroErrorFfi>)
  _lockExposurePtr = _dylib
      .lookup<
        NativeFunction<
          Void Function(Int64, Int64, Int64, Pointer<NitroErrorFfi>)
        >
      >('nitro_camera_lock_exposure')
      .asFunction<void Function(int, int, int, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final void Function(int, int, int, Pointer<NitroErrorFfi>)
  _lockFocusPtr = _dylib
      .lookup<
        NativeFunction<
          Void Function(Int64, Int64, Int64, Pointer<NitroErrorFfi>)
        >
      >('nitro_camera_lock_focus')
      .asFunction<void Function(int, int, int, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final void Function(int, int, int, Pointer<NitroErrorFfi>)
  _lockWhiteBalancePtr = _dylib
      .lookup<
        NativeFunction<
          Void Function(Int64, Int64, Int64, Pointer<NitroErrorFfi>)
        >
      >('nitro_camera_lock_white_balance')
      .asFunction<void Function(int, int, int, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final void Function(int, int, int, Pointer<NitroErrorFfi>)
  _setTargetOrientationPtr = _dylib
      .lookup<
        NativeFunction<
          Void Function(Int64, Int64, Int64, Pointer<NitroErrorFfi>)
        >
      >('nitro_camera_set_target_orientation')
      .asFunction<void Function(int, int, int, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final void Function(int, int, int, Pointer<NitroErrorFfi>)
  _setDistortionCorrectionPtr = _dylib
      .lookup<
        NativeFunction<
          Void Function(Int64, Int64, Int64, Pointer<NitroErrorFfi>)
        >
      >('nitro_camera_set_distortion_correction')
      .asFunction<void Function(int, int, int, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final void Function(int, int, Pointer<NitroErrorFfi>)
  _enableOrientationEventsPtr = _dylib
      .lookup<
        NativeFunction<Void Function(Int64, Int64, Pointer<NitroErrorFfi>)>
      >('nitro_camera_enable_orientation_events')
      .asFunction<void Function(int, int, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final void Function(int, int, Pointer<NitroErrorFfi>)
  _enableDeviceAvailabilityEventsPtr = _dylib
      .lookup<
        NativeFunction<Void Function(Int64, Int64, Pointer<NitroErrorFfi>)>
      >('nitro_camera_enable_device_availability_events')
      .asFunction<void Function(int, int, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final void Function(int, int, Pointer<Utf8>, Pointer<NitroErrorFfi>)
  _setNativeDetectorPtr = _dylib
      .lookupFunction<
        Void Function(Int64, Int64, Pointer<Utf8>, Pointer<NitroErrorFfi>),
        void Function(int, int, Pointer<Utf8>, Pointer<NitroErrorFfi>)
      >('nitro_camera_set_native_detector');
  late final Pointer<Utf8> Function(int, Pointer<NitroErrorFfi>)
  _getConcurrentCameraIdsJsonPtr = _dylib
      .lookupFunction<
        Pointer<Utf8> Function(Int64, Pointer<NitroErrorFfi>),
        Pointer<Utf8> Function(int, Pointer<NitroErrorFfi>)
      >('nitro_camera_get_concurrent_camera_ids_json');
  late final Pointer<Uint8> Function(int, int, Pointer<Void>)
  _takePhotoWithOptionsPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Int64, Int64, Pointer<Void>),
        Pointer<Uint8> Function(int, int, Pointer<Void>)
      >('nitro_camera_take_photo_with_options');
  late final Pointer<Uint8> Function(int, int) _takeSnapshotPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Int64, Int64),
        Pointer<Uint8> Function(int, int)
      >('nitro_camera_take_snapshot');
  late final void Function(int, Pointer<NitroErrorFfi>) _resetPtr = _dylib
      .lookup<NativeFunction<Void Function(Int64, Pointer<NitroErrorFfi>)>>(
        'nitro_camera_reset',
      )
      .asFunction<void Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final void Function(int, int) _registerFrameStreamPtr = _dylib
      .lookupFunction<Void Function(Int64, Int64), void Function(int, int)>(
        'nitro_camera_register_frame_stream_stream',
      );
  late final void Function(int) _releaseFrameStreamPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_camera_release_frame_stream_stream',
      );
  late final void Function(int, int) _registerEventStreamPtr = _dylib
      .lookupFunction<Void Function(Int64, Int64), void Function(int, int)>(
        'nitro_camera_register_event_stream_stream',
      );
  late final void Function(int) _releaseEventStreamPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_camera_release_event_stream_stream',
      );
  // ignore: unused_field
  late final Pointer<NitroErrorFfi> Function() _getErrorPtr = _dylib
      .lookupFunction<
        Pointer<NitroErrorFfi> Function(),
        Pointer<NitroErrorFfi> Function()
      >('nitro_camera_get_error');
  // ignore: unused_field
  late final void Function() _clearErrorPtr = _dylib
      .lookupFunction<Void Function(), void Function()>(
        'nitro_camera_clear_error',
      );
  // ignore: unused_field
  late final Pointer<NativeFunction<Pointer<NitroErrorFfi> Function()>>
  _getErrorNativePtr = _dylib.lookup('nitro_camera_get_error');
  // ignore: unused_field
  late final Pointer<NativeFunction<Void Function()>> _clearErrorNativePtr =
      _dylib.lookup('nitro_camera_clear_error');

  @override
  void dispose() {
    if (isDisposed) return;
    NitroRuntime.logLifecycle(
      'dispose(nitro_camera)',
      'disposing (instanceId=$_instanceId)',
    );
    _destroyInstancePtr(_instanceId);
    NitroRuntime.releaseLib('nitro_camera');
    _instances.remove(_instanceKey);
    NitroInstanceRegistry.unregister(_instanceId, this);
    calloc.free(_nitroErr); // S8: free pre-allocated error slot
    super.dispose(); // sets isDisposed = true, calls onDestroy()
    NitroRuntime.logLifecycle('dispose(nitro_camera)', 'disposed');
  }

  /// Opaque reference to this native impl — pass to other plugins via AnyNativeObject.
  AnyNativeObject get asAnyNativeObject => AnyNativeObject(_instanceId);

  @override
  Future<int> requestCameraPermission() async {
    checkDisposed();
    final res = await NitroRuntime.callAsync<int>(
      _requestCameraPermissionPtr,
      [_instanceId],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'requestCameraPermission',
    );
    return res;
  }

  @override
  int getCameraPermissionStatus() {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _getCameraPermissionStatusPtr(_instanceId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
      return res;
    }, methodName: 'getCameraPermissionStatus');
  }

  @override
  Future<int> requestMicrophonePermission() async {
    checkDisposed();
    final res = await NitroRuntime.callAsync<int>(
      _requestMicrophonePermissionPtr,
      [_instanceId],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'requestMicrophonePermission',
    );
    return res;
  }

  @override
  int getMicrophonePermissionStatus() {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _getMicrophonePermissionStatusPtr(_instanceId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
      return res;
    }, methodName: 'getMicrophonePermissionStatus');
  }

  @override
  Future<String> getAvailableCameraDevicesJson() async {
    checkDisposed();
    final res = await NitroRuntime.callAsync<Pointer<Utf8>>(
      _getAvailableCameraDevicesJsonPtr,
      [_instanceId],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'getAvailableCameraDevicesJson',
    );
    return res.toDartStringWithFree();
  }

  @override
  List<CameraDevice> getAvailableCameraDevices() {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _getAvailableCameraDevicesPtr(_instanceId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
      return LazyRecordList.decode(
        res,
        (r) => CameraDeviceRecordExt.fromReader(r),
      );
    }, methodName: 'getAvailableCameraDevices');
  }

  @override
  int getDeviceCount() {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _getDeviceCountPtr(_instanceId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
      return res;
    }, methodName: 'getDeviceCount');
  }

  @override
  CameraDevice getDevice(int index) {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _getDevicePtr(_instanceId, index, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
      final CameraDevice decoded;
      try {
        decoded = CameraDeviceRecordExt.fromNative(res);
      } finally {
        malloc.free(res);
      }
      return decoded;
    }, methodName: 'getDevice');
  }

  @override
  Future<int> openCamera(
    String deviceId,
    int width,
    int height,
    int fps,
    int enableAudio,
  ) async {
    checkDisposed();
    final arena = Arena();
    try {
      final res = await NitroRuntime.callAsync<int>(
        _openCameraPtr,
        [
          _instanceId,
          deviceId.toNativeUtf8(allocator: arena),
          width,
          height,
          fps,
          enableAudio,
        ],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'openCamera',
      );
      return res;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<void> closeCamera(int textureId) async {
    checkDisposed();
    await NitroRuntime.callAsync<void>(
      _closeCameraPtr,
      [_instanceId, textureId],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'closeCamera',
    );
  }

  @override
  void startPreview(int textureId) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _startPreviewPtr(_instanceId, textureId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'startPreview');
  }

  @override
  void stopPreview(int textureId) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _stopPreviewPtr(_instanceId, textureId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'stopPreview');
  }

  @override
  void setZoom(int textureId, double zoom) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _setZoomPtr(_instanceId, textureId, zoom, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'setZoom');
  }

  @override
  void setFocusPoint(int textureId, double x, double y) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _setFocusPointPtr(_instanceId, textureId, x, y, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'setFocusPoint');
  }

  @override
  void setAutoFocus(int textureId, int mode) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _setAutoFocusPtr(_instanceId, textureId, mode, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'setAutoFocus');
  }

  @override
  void setExposure(int textureId, double value) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _setExposurePtr(_instanceId, textureId, value, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'setExposure');
  }

  @override
  void setFlash(int textureId, int mode) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _setFlashPtr(_instanceId, textureId, mode, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'setFlash');
  }

  @override
  void setTorch(int textureId, int enabled) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _setTorchPtr(_instanceId, textureId, enabled, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'setTorch');
  }

  @override
  void setWhiteBalance(int textureId, int temperature) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _setWhiteBalancePtr(_instanceId, textureId, temperature, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'setWhiteBalance');
  }

  @override
  void setHdr(int textureId, int enabled) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _setHdrPtr(_instanceId, textureId, enabled, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'setHdr');
  }

  @override
  Future<PhotoResult> takePhoto(int textureId) async {
    checkDisposed();
    final rawPtr = await NitroRuntime.callAsync<Pointer<Uint8>>(
      _takePhotoPtr,
      [_instanceId, textureId],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'takePhoto',
    );
    final PhotoResult decoded;
    try {
      decoded = PhotoResultRecordExt.fromNative(rawPtr);
    } finally {
      malloc.free(rawPtr);
    }
    return decoded;
  }

  @override
  Future<void> startVideoRecording(
    int textureId,
    String outputPath,
    RecordingOptions options,
  ) async {
    checkDisposed();
    final arena = Arena();
    try {
      await NitroRuntime.callAsync<void>(
        _startVideoRecordingPtr,
        [
          _instanceId,
          textureId,
          outputPath.toNativeUtf8(allocator: arena),
          options.toNative(arena).cast<Void>(),
        ],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'startVideoRecording',
      );
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<RecordingResult> stopVideoRecording(int textureId) async {
    checkDisposed();
    final rawPtr = await NitroRuntime.callAsync<Pointer<Uint8>>(
      _stopVideoRecordingPtr,
      [_instanceId, textureId],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'stopVideoRecording',
    );
    final RecordingResult decoded;
    try {
      decoded = RecordingResultRecordExt.fromNative(rawPtr);
    } finally {
      malloc.free(rawPtr);
    }
    return decoded;
  }

  @override
  void pauseRecording(int textureId) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _pauseRecordingPtr(_instanceId, textureId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'pauseRecording');
  }

  @override
  void resumeRecording(int textureId) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _resumeRecordingPtr(_instanceId, textureId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'resumeRecording');
  }

  @override
  void cancelRecording(int textureId) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _cancelRecordingPtr(_instanceId, textureId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'cancelRecording');
  }

  @override
  void enableFrameProcessing(int textureId, int enabled) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _enableFrameProcessingPtr(_instanceId, textureId, enabled, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'enableFrameProcessing');
  }

  @override
  void setFrameFormat(int textureId, int format) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _setFrameFormatPtr(_instanceId, textureId, format, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'setFrameFormat');
  }

  @override
  void setSamplingRate(int textureId, int samplingRate) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _setSamplingRatePtr(_instanceId, textureId, samplingRate, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'setSamplingRate');
  }

  @override
  void setFilterShader(int textureId, String shaderSource) {
    checkDisposed();
    NitroRuntime.callSync<void>(
      () => withArena((arena) {
        _setFilterShaderPtr(
          _instanceId,
          textureId,
          shaderSource.toNativeUtf8(allocator: arena),
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr);
      }),
      methodName: 'setFilterShader',
    );
  }

  @override
  void updateOverlay(int textureId, Uint8List overlayData) {
    checkDisposed();
    NitroRuntime.callSync<void>(
      () => withArena((arena) {
        _updateOverlayPtr(
          _instanceId,
          textureId,
          overlayData.toPointer(arena),
          overlayData.length,
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr);
      }),
      methodName: 'updateOverlay',
    );
  }

  @override
  Future<ResolvedConfig> configure(int textureId, CameraConfig config) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Void>>(
        _configurePtr,
        [_instanceId, textureId, config.toNative(arena).cast<Void>()],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'configure',
      );
      if (rawPtr == nullptr) {
        throw StateError('configure returned null');
      }
      final structPtr = Pointer<ResolvedConfigFfi>.fromAddress(rawPtr.address);
      final ResolvedConfig decoded;
      try {
        decoded = structPtr.ref.toDart();
      } finally {
        structPtr.ref.freeFields();
        malloc.free(structPtr);
      }
      return decoded;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  String getSessionStateJson(int textureId) {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _getSessionStateJsonPtr(_instanceId, textureId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
      return res.toDartStringWithFree();
    }, methodName: 'getSessionStateJson');
  }

  @override
  void setVideoStabilization(int textureId, int mode) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _setVideoStabilizationPtr(_instanceId, textureId, mode, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'setVideoStabilization');
  }

  @override
  void setLowLightBoost(int textureId, int enabled) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _setLowLightBoostPtr(_instanceId, textureId, enabled, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'setLowLightBoost');
  }

  @override
  void setTorchLevel(int textureId, double level) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _setTorchLevelPtr(_instanceId, textureId, level, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'setTorchLevel');
  }

  @override
  void lockExposure(int textureId, int locked) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _lockExposurePtr(_instanceId, textureId, locked, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'lockExposure');
  }

  @override
  void lockFocus(int textureId, int locked) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _lockFocusPtr(_instanceId, textureId, locked, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'lockFocus');
  }

  @override
  void lockWhiteBalance(int textureId, int locked) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _lockWhiteBalancePtr(_instanceId, textureId, locked, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'lockWhiteBalance');
  }

  @override
  void setTargetOrientation(int textureId, int degrees) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _setTargetOrientationPtr(_instanceId, textureId, degrees, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'setTargetOrientation');
  }

  @override
  void setDistortionCorrection(int textureId, int enabled) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _setDistortionCorrectionPtr(_instanceId, textureId, enabled, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'setDistortionCorrection');
  }

  @override
  void enableOrientationEvents(int enabled) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _enableOrientationEventsPtr(_instanceId, enabled, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'enableOrientationEvents');
  }

  @override
  void enableDeviceAvailabilityEvents(int enabled) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _enableDeviceAvailabilityEventsPtr(_instanceId, enabled, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'enableDeviceAvailabilityEvents');
  }

  @override
  void setNativeDetector(int textureId, String detector) {
    checkDisposed();
    NitroRuntime.callSync<void>(
      () => withArena((arena) {
        _setNativeDetectorPtr(
          _instanceId,
          textureId,
          detector.toNativeUtf8(allocator: arena),
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr);
      }),
      methodName: 'setNativeDetector',
    );
  }

  @override
  String getConcurrentCameraIdsJson() {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _getConcurrentCameraIdsJsonPtr(_instanceId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
      return res.toDartStringWithFree();
    }, methodName: 'getConcurrentCameraIdsJson');
  }

  @override
  Future<PhotoResult> takePhotoWithOptions(
    int textureId,
    PhotoOptions options,
  ) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Uint8>>(
        _takePhotoWithOptionsPtr,
        [_instanceId, textureId, options.toNative(arena).cast<Void>()],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'takePhotoWithOptions',
      );
      final PhotoResult decoded;
      try {
        decoded = PhotoResultRecordExt.fromNative(rawPtr);
      } finally {
        malloc.free(rawPtr);
      }
      return decoded;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<PhotoResult> takeSnapshot(int textureId) async {
    checkDisposed();
    final rawPtr = await NitroRuntime.callAsync<Pointer<Uint8>>(
      _takeSnapshotPtr,
      [_instanceId, textureId],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'takeSnapshot',
    );
    final PhotoResult decoded;
    try {
      decoded = PhotoResultRecordExt.fromNative(rawPtr);
    } finally {
      malloc.free(rawPtr);
    }
    return decoded;
  }

  @override
  void reset() {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _resetPtr(_instanceId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'reset');
  }

  @override
  Stream<CameraFrame> get frameStream {
    checkDisposed();
    return NitroRuntime.openStream<CameraFrameProxy>(
      register: (port) => _registerFrameStreamPtr(_instanceId, port),
      unpack: (message) {
        if (message == null) {
          throw StateError(
            'Received null event on non-nullable stream frameStream',
          );
        }
        return CameraFrameProxy(
          Pointer<CameraFrameFfi>.fromAddress(message as int),
        );
      },
      release: (port) => _releaseFrameStreamPtr(port),
      backpressure: Backpressure.dropLatest,
    );
  }

  @override
  Stream<CameraEvent> get eventStream {
    checkDisposed();
    return NitroRuntime.openStream<CameraEvent>(
      register: (port) => _registerEventStreamPtr(_instanceId, port),
      unpack: (message) {
        if (message == null) {
          throw StateError(
            'Received null event on non-nullable stream eventStream',
          );
        }
        final rawPtr = Pointer<Uint8>.fromAddress(message as int);
        try {
          return CameraEventRecordExt.fromNative(rawPtr);
        } finally {
          malloc.free(rawPtr);
        }
      },
      release: (port) => _releaseEventStreamPtr(port),
      backpressure: Backpressure.bufferDrop,
    );
  }
}

extension NitroCameraNativeRef on NitroCamera {
  AnyNativeObject get asAnyNativeObject =>
      (this as _NitroCameraImpl).asAnyNativeObject;
}
