// Generated by Nitrogen Modules. Do not edit.
part of 'nitro_camera.native.dart';

// --- Enum FFI helpers (generated by Nitrogen) ---

extension CameraPositionNativeExt on CameraPosition {
  int get nativeValue => index + 0;
}

extension CameraPositionFromNativeExt on int {
  CameraPosition toCameraPosition() => CameraPosition.values[this - 0];
}

extension CameraLensTypeNativeExt on CameraLensType {
  int get nativeValue => index + 0;
}

extension CameraLensTypeFromNativeExt on int {
  CameraLensType toCameraLensType() => CameraLensType.values[this - 0];
}

extension FlashModeNativeExt on FlashMode {
  int get nativeValue => index + 0;
}

extension FlashModeFromNativeExt on int {
  FlashMode toFlashMode() => FlashMode.values[this - 0];
}

extension AutoFocusModeNativeExt on AutoFocusMode {
  int get nativeValue => index + 0;
}

extension AutoFocusModeFromNativeExt on int {
  AutoFocusMode toAutoFocusMode() => AutoFocusMode.values[this - 0];
}

extension PermissionStatusNativeExt on PermissionStatus {
  int get nativeValue => index + 0;
}

extension PermissionStatusFromNativeExt on int {
  PermissionStatus toPermissionStatus() => PermissionStatus.values[this - 0];
}

// --- Struct FFI representations (generated by Nitrogen) ---

@Packed(1)
final class CameraDeviceFfi extends Struct {
  external Pointer<Utf8> id;
  external Pointer<Utf8> name;
  @Int64()
  external int position;
  @Int64()
  external int lensType;
  @Int64()
  external int sensorOrientation;
  @Double()
  external double minZoom;
  @Double()
  external double maxZoom;
  @Double()
  external double neutralZoom;
  @Int64()
  external int hasFlash;
  @Int64()
  external int hasTorch;
  @Int64()
  external int maxPhotoWidth;
  @Int64()
  external int maxPhotoHeight;
}

extension CameraDeviceFfiExt on CameraDeviceFfi {
  CameraDevice toDart() {
    return CameraDevice(
      id: id.toDartString(),
      name: name.toDartString(),
      position: position,
      lensType: lensType,
      sensorOrientation: sensorOrientation,
      minZoom: minZoom,
      maxZoom: maxZoom,
      neutralZoom: neutralZoom,
      hasFlash: hasFlash,
      hasTorch: hasTorch,
      maxPhotoWidth: maxPhotoWidth,
      maxPhotoHeight: maxPhotoHeight,
    );
  }
}

extension CameraDeviceExt on CameraDevice {
  Pointer<CameraDeviceFfi> toNative(Arena arena) {
    final ptr = arena<CameraDeviceFfi>();
    ptr.ref.id = id.toNativeUtf8(allocator: arena);
    ptr.ref.name = name.toNativeUtf8(allocator: arena);
    ptr.ref.position = position;
    ptr.ref.lensType = lensType;
    ptr.ref.sensorOrientation = sensorOrientation;
    ptr.ref.minZoom = minZoom;
    ptr.ref.maxZoom = maxZoom;
    ptr.ref.neutralZoom = neutralZoom;
    ptr.ref.hasFlash = hasFlash;
    ptr.ref.hasTorch = hasTorch;
    ptr.ref.maxPhotoWidth = maxPhotoWidth;
    ptr.ref.maxPhotoHeight = maxPhotoHeight;
    return ptr;
  }
}

final class CameraFrameFfi extends Struct {
  external Pointer<Uint8> pixels;
  @Int64()
  external int size;
  @Int64()
  external int width;
  @Int64()
  external int height;
  @Int64()
  external int timestamp;
  @Int64()
  external int orientation;
  @Int64()
  external int textureId;
}

extension CameraFrameFfiExt on CameraFrameFfi {
  CameraFrame toDart() {
    return CameraFrame(
      pixels: pixels.asTypedList(size),
      size: size,
      width: width,
      height: height,
      timestamp: timestamp,
      orientation: orientation,
      textureId: textureId,
    );
  }
}

extension CameraFrameExt on CameraFrame {
  Pointer<CameraFrameFfi> toNative(Arena arena) {
    final ptr = arena<CameraFrameFfi>();
    ptr.ref.pixels = pixels.toPointer(arena);
    ptr.ref.size = size;
    ptr.ref.width = width;
    ptr.ref.height = height;
    ptr.ref.timestamp = timestamp;
    ptr.ref.orientation = orientation;
    ptr.ref.textureId = textureId;
    return ptr;
  }
}

@Packed(1)
final class PhotoResultFfi extends Struct {
  external Pointer<Utf8> path;
  @Int64()
  external int width;
  @Int64()
  external int height;
  @Int64()
  external int fileSize;
}

extension PhotoResultFfiExt on PhotoResultFfi {
  PhotoResult toDart() {
    return PhotoResult(
      path: path.toDartString(),
      width: width,
      height: height,
      fileSize: fileSize,
    );
  }
}

extension PhotoResultExt on PhotoResult {
  Pointer<PhotoResultFfi> toNative(Arena arena) {
    final ptr = arena<PhotoResultFfi>();
    ptr.ref.path = path.toNativeUtf8(allocator: arena);
    ptr.ref.width = width;
    ptr.ref.height = height;
    ptr.ref.fileSize = fileSize;
    return ptr;
  }
}

@Packed(1)
final class RecordingResultFfi extends Struct {
  external Pointer<Utf8> path;
  @Int64()
  external int durationMs;
  @Int64()
  external int fileSize;
}

extension RecordingResultFfiExt on RecordingResultFfi {
  RecordingResult toDart() {
    return RecordingResult(
      path: path.toDartString(),
      durationMs: durationMs,
      fileSize: fileSize,
    );
  }
}

extension RecordingResultExt on RecordingResult {
  Pointer<RecordingResultFfi> toNative(Arena arena) {
    final ptr = arena<RecordingResultFfi>();
    ptr.ref.path = path.toNativeUtf8(allocator: arena);
    ptr.ref.durationMs = durationMs;
    ptr.ref.fileSize = fileSize;
    return ptr;
  }
}

class _NitroCameraImpl extends NitroCamera {
  final DynamicLibrary _dylib;

  _NitroCameraImpl() : _dylib = NitroRuntime.loadLib('nitro_camera') {
    final initFunc = _dylib.lookupFunction<IntPtr Function(Pointer<Void>), int Function(Pointer<Void>)>('InitDartApiDL');
    initFunc(NativeApi.initializeApiDLData);
  }

  late final int Function() _requestCameraPermissionPtr = _dylib.lookupFunction<Int64 Function(), int Function()>('nitro_camera_request_camera_permission');
  late final int Function() _getCameraPermissionStatusPtr = _dylib.lookupFunction<Int64 Function(), int Function()>('nitro_camera_get_camera_permission_status');
  late final int Function() _getDeviceCountPtr = _dylib.lookupFunction<Int64 Function(), int Function()>('nitro_camera_get_device_count');
  late final Pointer<Void> Function(int) _getDevicePtr = _dylib.lookupFunction<Pointer<Void> Function(Int64), Pointer<Void> Function(int)>('nitro_camera_get_device');
  late final int Function(Pointer<Utf8>, int, int, int, int) _openCameraPtr = _dylib.lookupFunction<Int64 Function(Pointer<Utf8>, Int64, Int64, Int64, Int64), int Function(Pointer<Utf8>, int, int, int, int)>('nitro_camera_open_camera');
  late final void Function(int) _closeCameraPtr = _dylib.lookupFunction<Void Function(Int64), void Function(int)>('nitro_camera_close_camera');
  late final void Function(int) _startPreviewPtr = _dylib.lookupFunction<Void Function(Int64), void Function(int)>('nitro_camera_start_preview');
  late final void Function(int) _stopPreviewPtr = _dylib.lookupFunction<Void Function(Int64), void Function(int)>('nitro_camera_stop_preview');
  late final void Function(int, double) _setZoomPtr = _dylib.lookupFunction<Void Function(Int64, Double), void Function(int, double)>('nitro_camera_set_zoom');
  late final void Function(int, double, double) _setFocusPointPtr = _dylib.lookupFunction<Void Function(Int64, Double, Double), void Function(int, double, double)>('nitro_camera_set_focus_point');
  late final void Function(int, int) _setAutoFocusPtr = _dylib.lookupFunction<Void Function(Int64, Int64), void Function(int, int)>('nitro_camera_set_auto_focus');
  late final void Function(int, double) _setExposurePtr = _dylib.lookupFunction<Void Function(Int64, Double), void Function(int, double)>('nitro_camera_set_exposure');
  late final void Function(int, int) _setFlashPtr = _dylib.lookupFunction<Void Function(Int64, Int64), void Function(int, int)>('nitro_camera_set_flash');
  late final void Function(int, int) _setTorchPtr = _dylib.lookupFunction<Void Function(Int64, Int64), void Function(int, int)>('nitro_camera_set_torch');
  late final void Function(int, int) _setWhiteBalancePtr = _dylib.lookupFunction<Void Function(Int64, Int64), void Function(int, int)>('nitro_camera_set_white_balance');
  late final void Function(int, int) _setHdrPtr = _dylib.lookupFunction<Void Function(Int64, Int64), void Function(int, int)>('nitro_camera_set_hdr');
  late final Pointer<Void> Function(int) _takePhotoPtr = _dylib.lookupFunction<Pointer<Void> Function(Int64), Pointer<Void> Function(int)>('nitro_camera_take_photo');
  late final void Function(int, Pointer<Utf8>) _startVideoRecordingPtr = _dylib.lookupFunction<Void Function(Int64, Pointer<Utf8>), void Function(int, Pointer<Utf8>)>('nitro_camera_start_video_recording');
  late final Pointer<Void> Function(int) _stopVideoRecordingPtr = _dylib.lookupFunction<Pointer<Void> Function(Int64), Pointer<Void> Function(int)>('nitro_camera_stop_video_recording');
  late final void Function(int, int) _enableFrameProcessingPtr = _dylib.lookupFunction<Void Function(Int64, Int64), void Function(int, int)>('nitro_camera_enable_frame_processing');
  late final void Function(int) _registerFrameStreamPtr = _dylib.lookupFunction<Void Function(Int64), void Function(int)>('nitro_camera_register_frame_stream_stream');
  late final void Function(int) _releaseFrameStreamPtr = _dylib.lookupFunction<Void Function(Int64), void Function(int)>('nitro_camera_release_frame_stream_stream');
  @override
  // ignore: unnecessary_overrides
  void dispose() {
    super.dispose(); // sets isDisposed = true, calls onDestroy()
  }

  @override
  Future<int> requestCameraPermission() async {
    checkDisposed();
    return NitroRuntime.callAsync(_requestCameraPermissionPtr, []);
  }

  @override
  Future<int> getCameraPermissionStatus() async {
    checkDisposed();
    return NitroRuntime.callAsync(_getCameraPermissionStatusPtr, []);
  }

  @override
  Future<int> getDeviceCount() async {
    checkDisposed();
    return NitroRuntime.callAsync(_getDeviceCountPtr, []);
  }

  @override
  Future<CameraDevice> getDevice(int index) async {
    checkDisposed();
    final asyncResult = await NitroRuntime.callAsync(_getDevicePtr, [index]);
    return Pointer<CameraDeviceFfi>.fromAddress((asyncResult as Pointer<Void>).address).ref.toDart();
  }

  @override
  Future<int> openCamera(String deviceId, int width, int height, int fps, int enableAudio) async {
    checkDisposed();
    return withArena((arena) async {
      final result = await NitroRuntime.callAsync(_openCameraPtr, [deviceId.toNativeUtf8(allocator: arena), width, height, fps, enableAudio]);
      return result;
    });
  }

  @override
  Future<void> closeCamera(int textureId) async {
    checkDisposed();
    return NitroRuntime.callAsync(_closeCameraPtr, [textureId]);
  }

  @override
  Future<void> startPreview(int textureId) async {
    checkDisposed();
    return NitroRuntime.callAsync(_startPreviewPtr, [textureId]);
  }

  @override
  Future<void> stopPreview(int textureId) async {
    checkDisposed();
    return NitroRuntime.callAsync(_stopPreviewPtr, [textureId]);
  }

  @override
  Future<void> setZoom(int textureId, double zoom) async {
    checkDisposed();
    return NitroRuntime.callAsync(_setZoomPtr, [textureId, zoom]);
  }

  @override
  Future<void> setFocusPoint(int textureId, double x, double y) async {
    checkDisposed();
    return NitroRuntime.callAsync(_setFocusPointPtr, [textureId, x, y]);
  }

  @override
  Future<void> setAutoFocus(int textureId, int mode) async {
    checkDisposed();
    return NitroRuntime.callAsync(_setAutoFocusPtr, [textureId, mode]);
  }

  @override
  Future<void> setExposure(int textureId, double value) async {
    checkDisposed();
    return NitroRuntime.callAsync(_setExposurePtr, [textureId, value]);
  }

  @override
  Future<void> setFlash(int textureId, int mode) async {
    checkDisposed();
    return NitroRuntime.callAsync(_setFlashPtr, [textureId, mode]);
  }

  @override
  Future<void> setTorch(int textureId, int enabled) async {
    checkDisposed();
    return NitroRuntime.callAsync(_setTorchPtr, [textureId, enabled]);
  }

  @override
  Future<void> setWhiteBalance(int textureId, int temperature) async {
    checkDisposed();
    return NitroRuntime.callAsync(_setWhiteBalancePtr, [textureId, temperature]);
  }

  @override
  Future<void> setHdr(int textureId, int enabled) async {
    checkDisposed();
    return NitroRuntime.callAsync(_setHdrPtr, [textureId, enabled]);
  }

  @override
  Future<PhotoResult> takePhoto(int textureId) async {
    checkDisposed();
    final asyncResult = await NitroRuntime.callAsync(_takePhotoPtr, [textureId]);
    return Pointer<PhotoResultFfi>.fromAddress((asyncResult as Pointer<Void>).address).ref.toDart();
  }

  @override
  Future<void> startVideoRecording(int textureId, String outputPath) async {
    checkDisposed();
    return withArena((arena) async {
      final result = await NitroRuntime.callAsync(_startVideoRecordingPtr, [textureId, outputPath.toNativeUtf8(allocator: arena)]);
      return result;
    });
  }

  @override
  Future<RecordingResult> stopVideoRecording(int textureId) async {
    checkDisposed();
    final asyncResult = await NitroRuntime.callAsync(_stopVideoRecordingPtr, [textureId]);
    return Pointer<RecordingResultFfi>.fromAddress((asyncResult as Pointer<Void>).address).ref.toDart();
  }

  @override
  Future<void> enableFrameProcessing(int textureId, int enabled) async {
    checkDisposed();
    return NitroRuntime.callAsync(_enableFrameProcessingPtr, [textureId, enabled]);
  }

  @override
  Stream<CameraFrame> get frameStream {
    checkDisposed();
    return NitroRuntime.openStream<CameraFrame>(
      register: (port) => _registerFrameStreamPtr(port),
      unpack: (rawPtr) => Pointer<CameraFrameFfi>.fromAddress(rawPtr).ref.toDart(),
      release: (port) => _releaseFrameStreamPtr(port),
      backpressure: Backpressure.dropLatest,
    );
  }

}
