// Generated by Nitrogen Modules. Do not edit.
part of 'nitro_camera.native.dart';

class _NitroCameraImpl extends NitroCamera {
  final DynamicLibrary _dylib;

  _NitroCameraImpl() : _dylib = NitroRuntime.loadLib('nitro_camera') {
    final initFunc = _dylib.lookupFunction<IntPtr Function(Pointer<Void>), int Function(Pointer<Void>)>('InitDartApiDL');
    initFunc(NativeApi.initializeApiDLData);
  }

  late final double Function(double, double) _addPtr = _dylib.lookupFunction<Double Function(Double, Double), double Function(double, double)>('nitro_camera_add');
  late final Pointer<Utf8> Function(Pointer<Utf8>) _getGreetingPtr = _dylib.lookupFunction<Pointer<Utf8> Function(Pointer<Utf8>), Pointer<Utf8> Function(Pointer<Utf8>)>('nitro_camera_get_greeting');
  @override
  // ignore: unnecessary_overrides
  void dispose() {
    super.dispose(); // sets isDisposed = true, calls onDestroy()
  }

  @override
  double add(double a, double b) {
    checkDisposed();
    return _addPtr(a, b);
  }

  @override
  Future<String> getGreeting(String name) async {
    checkDisposed();
    return withArena((arena) async {
      final result = await NitroRuntime.callAsync(_getGreetingPtr, [name.toNativeUtf8(allocator: arena)]);
      return (result as Pointer<Utf8>).toDartStringWithFree();
    });
  }

}
