package dev.shreeman.nitro_camera

import android.content.Context
import nitro.nitro_camera_module.HybridNitroCameraSpec

/// Native implementation of HybridNitroCameraSpec.
/// This file is yours to edit — the interface is generated by `nitrogen generate`.
class NitroCameraImpl(private val context: Context) : HybridNitroCameraSpec {

    override fun add(a: Double, b: Double): Double = a + b + a *b

    override suspend fun getGreeting(name: String): String = "Hello, $name! from Nitro!!!"
}
